[project]
name = "jellyfin-api-client"
version = "10.11.0"
description = "A client library for accessing Jellyfin API"
authors = [
    {name = "Geoffrey Coulaud", email = "geoffrey.coulaud@gmail.com"},
    {name = "Paul Hutchings", email = "dev@studiop.page"},
]
license = {text = "MIT"}
requires-python = "<4.0,>=3.10"
dependencies = [
    "httpx>=0.28.1",
    "attrs>=25.3.0",
    "python-dateutil>=2.9.0.post0"

]
readme = "README.md"
keywords = [
    "jellyfin",
    "api",
    "openapi",
]

[project.urls]
repository = "https://github.com/studioph/jellyfin-api-client"


[tool.pdm.scripts]
gen = { cmd = [
  "openapi-python-client",
  "generate",
  "--meta",
  "none",
  "--path",
  "specs/jellyfin-openapi-stable.json",
  "--config",
  "openapi-config.yaml",
  "--output-path",
  "src/jellyfin",
  "--overwrite"
] }


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.black]
line-length = 120
target-version = ['py310', 'py311', 'py312', 'py313']
exclude = '''
(
  /(
    | \.git
    | \.venv
    | \.mypy_cache
  )/
)
'''

[tool.isort]
line_length = 120
profile = "black"

[tool.pdm.build]
excludes = ["**/.ruff_cache/"]

[dependency-groups]
dev = [
    "pylint>=3.3.7",
    "black>=25.1.0",
    "isort>=6.0.1",
    "openapi-python-client>=0.25.3",
]
